cmd.set('orthoscopic', True)
cmd.set('antialias', 2)
cmd.set('ray_shadows','off')
cmd.set('ray_texture', 1)
cmd.set('ray_trace_mode', 1)
cmd.set('ray_trace_color', 'grey20')
cmd.set('ambient', 0.3)
cmd.set('ray_opaque_background', 0)
cmd.color('skyblue', '(name N*)')
cmd.color('white', '(name H*)')
cmd.color('tv_red', '(name O*)')
cmd.set('spec_power', 1500)
cmd.set('spec_reflect', 0)